"""update poem

Revision ID: 1ba19d4f3a2e
Revises: 1710cf4fce96
Create Date: 2020-02-03 12:19:51.810264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba19d4f3a2e'
down_revision = '1710cf4fce96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem', sa.Column('flag', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_poem_flag'), 'poem', ['flag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poem_flag'), table_name='poem')
    op.drop_column('poem', 'flag')
    # ### end Alembic commands ###
