"""add marked_by

Revision ID: 69eec509862a
Revises: 8e8a8bb059c3
Create Date: 2020-02-05 15:11:03.883815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69eec509862a'
down_revision = '8e8a8bb059c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem', sa.Column('marked_by', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poem', 'marked_by')
    # ### end Alembic commands ###
