"""img tables

Revision ID: 8311d95e3649
Revises: 
Create Date: 2020-01-17 16:36:56.109306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8311d95e3649'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poem', sa.String(length=500), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('chosen', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_keyword'), 'poem', ['keyword'], unique=False)
    op.create_index(op.f('ix_poem_poem'), 'poem', ['poem'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poem_poem'), table_name='poem')
    op.drop_index(op.f('ix_poem_keyword'), table_name='poem')
    op.drop_table('poem')
    # ### end Alembic commands ###
