"""update time_stamp

Revision ID: ab66c6dd082b
Revises: 
Create Date: 2020-02-04 12:54:37.599868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab66c6dd082b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poem', sa.String(length=500), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('chosen', sa.String(length=200), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_flag'), 'poem', ['flag'], unique=False)
    op.create_index(op.f('ix_poem_keyword'), 'poem', ['keyword'], unique=False)
    op.create_index(op.f('ix_poem_poem'), 'poem', ['poem'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_poem_poem'), table_name='poem')
    op.drop_index(op.f('ix_poem_keyword'), table_name='poem')
    op.drop_index(op.f('ix_poem_flag'), table_name='poem')
    op.drop_table('poem')
    # ### end Alembic commands ###
