"""add confirmed_by

Revision ID: aca00b96afa7
Revises: 69eec509862a
Create Date: 2020-02-05 16:49:48.870020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca00b96afa7'
down_revision = '69eec509862a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem', sa.Column('confirmed_by', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poem', 'confirmed_by')
    # ### end Alembic commands ###
